In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [3]:
ar = np.array(33)
print("\n",ar)

ar = np.array([1, 2, 3, 4])
print("\n",ar)

ar = np.array([[1, 2, 3], [4, 5, 6]])
print("\n",ar)

ar = np.array([[[1, 2, 3], [4, 5, 6]], [[6, 7, 8], [10, 11, 12]]])
print("\n",ar)


 33

 [1 2 3 4]

 [[1 2 3]
 [4 5 6]]

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [10 11 12]]]


In [4]:
a = np.array(33)  #Check Number of Dimensions
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[6, 7, 8], [10, 11, 12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [6]:
arr = np.array([1, 2, 3, 4])

print("\n",arr[0])
print("\n",arr[1])
print("\n",arr[2] + arr[3])


 1

 2

 7


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])   #Access Array Elements

print('2nd element on 1st row: \n', arr[0, 1])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: \n', arr[1, 4])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[6, 7, 8], [10, 11, 12]]])

print(arr[0, 1, 2])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: \n', arr[1, -1])

2nd element on 1st row: 
 2
5th element on 2nd row: 
 10
6
Last element from 2nd dim: 
 10


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:3])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [9]:
arr = np.array([[1, 2, 3],[10, 11, 12]])

print(arr[1, 1:4])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("\n",arr[0:2, 2])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("\n",arr[0:2, 1:4])

[11 12]

 [3 8]

 [[2 3 4]
 [7 8 9]]


In [10]:
arr = np.array(['shakib', 'tanha', 'wasenat'])

print("\n",arr.dtype)
arr = np.array([1, 2, 3, 4], dtype='S')

print("\n",arr)
print("\n",arr.dtype)

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print("\n",newarr)
print("\n",newarr.dtype)


 <U7

 [b'1' b'2' b'3' b'4']

 |S1

 [1 2 3]

 int32


In [11]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [12]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

#change in view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)
#if Array Owns its Data
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[1 2 3 4 5]
